// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Wb9mVWEljaRGFO4hBd1CR2kYuFNXV-4',
    appId: '1:372857966232:web:a9956bcd3886531c950aed',
    messagingSenderId: '372857966232',
    projectId: 'employability-training-skill',
    authDomain: 'employability-training-skill.firebaseapp.com',
    storageBucket: 'employability-training-skill.appspot.com',
    measurementId: 'G-756R3RZQD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXt0y4xOSPUsHEoLV6pBcQceblTMPCMQ',
    appId: '1:372857966232:android:929014c8e0a7a7aa950aed',
    messagingSenderId: '372857966232',
    projectId: 'employability-training-skill',
    storageBucket: 'employability-training-skill.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfORu3hzxjs1iBN2O5A5i5tlyk-to6P68',
    appId: '1:372857966232:ios:de4450b43a7c9a31950aed',
    messagingSenderId: '372857966232',
    projectId: 'employability-training-skill',
    storageBucket: 'employability-training-skill.appspot.com',
    iosBundleId: 'com.hariapp.employabilityskillapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfORu3hzxjs1iBN2O5A5i5tlyk-to6P68',
    appId: '1:372857966232:ios:5190f90ed766052f950aed',
    messagingSenderId: '372857966232',
    projectId: 'employability-training-skill',
    storageBucket: 'employability-training-skill.appspot.com',
    iosBundleId: 'com.hariapp.employabilityskillapp.RunnerTests',
  );
}
